/**
 * Form Submit Handler — Shared evaluate-and-persist logic
 * ══════════════════════════════════════════════════════════════════
 * Centralizes the submit flow for ALL 6 loan forms:
 *   1. Call /api/evaluate-and-persist with formState
 *   2. Handle error responses with specific messages (402, 429, etc.)
 *   3. Store minimal metadata in sessionStorage
 *   4. Fire-and-forget eligibility-sync
 *   5. Navigate to /evaluating
 *
 * Before: Each form had its own submit logic (unsecured forms were broken).
 * After: One shared function, consistent behavior across all 6 loan types.
 * ══════════════════════════════════════════════════════════════════
 */

import { goto } from '$app/navigation';
import { browser } from '$app/environment';
import { secureFetch } from '$lib/utils/csrf';
import { safeSessionStorage } from '$lib/utils/safeStorage';

// ── Types ────────────────────────────────────────────────────────

export interface SubmitOptions {
	/** e.g. "Home Loan", "Personal Loan", "Business Loan - Unsecured" */
	loanType: string;

	/** Human-readable display name for the evaluating animation */
	loanDisplayName: string;

	/**
	 * Full form state serialized via formState.toJSON().
	 * Typed as `unknown` to accept both the FormState interface and
	 * plain objects — JSON.stringify handles either correctly.
	 */
	formStateJson: unknown;

	/** Applicant relationships (from userRelationships store) */
	relationships: Array<{
		fromId: string;
		toId: string;
		relationType: string;
		category?: string;
	}>;

	/** If editing an existing case, pass the caseId from URL query */
	editCaseId?: string;

	/**
	 * Quota-blocked-cases (S1): set to `true` when re-submitting after the
	 * client showed the save-prompt and the DSA chose Save. The server
	 * persists the case at stage='quota_blocked' (no offers computed) and
	 * auto-processes it FIFO on plan upgrade or monthly cycle reset.
	 * See docs/specs/QUOTA-BLOCKED-CASES-SPEC.md.
	 */
	saveToBuffer?: boolean;

	/**
	 * Client-generated UUID stamped onto a single logical submission.
	 * If the silent auto-retry in /evaluating fires after a 504, BOTH
	 * attempts share the same key — the server uses it to dedupe so a
	 * function that completed past the gateway timeout doesn't produce
	 * a duplicate case on the retry. Generated by submitFormForEvaluation
	 * the moment the DSA clicks Confirm; persists through the nav to
	 * /evaluating via the sessionStorage stash.
	 *
	 * Optional — older callers that don't set it lose dedupe protection
	 * but otherwise behave as before.
	 */
	idempotencyKey?: string;
}

/**
 * Structured upgrade prompt from a 402 quota-related response.
 *
 * `recommended_plan_limit` is `null` for the Enterprise tier (Infinity
 * cases). The modal renders "Unlimited" in that case.
 */
export interface UpgradePrompt {
	plan_id: string;
	plan_name: string;
	plan_limit: number;
	current_count: number;
	recommended_plan: string;
	recommended_plan_name: string;
	recommended_plan_limit: number | null;
}

/**
 * Buffer state from a 402 `quota_buffer_available` or `quota_fully_exhausted`
 * response. Drives the save-prompt copy ("3 of 5 save slots remaining").
 */
export interface BufferState {
	used: number;
	capacity: number;
	remaining: number;
}

export interface SubmitResult {
	/** Whether the submit succeeded — if false, check `error` */
	success: boolean;

	/** Human-readable error message (only when success=false) */
	error?: string;

	/** Error code from the server, useful for conditional UI */
	code?: string;

	/**
	 * Structured upgrade prompt — present on `quota_buffer_available`
	 * and `quota_fully_exhausted` 402 responses. Callers should branch
	 * on this BEFORE rendering `error` as a dead-end string — the modal
	 * flow (save-prompt or upgrade-required) is the right UX.
	 */
	upgradePrompt?: UpgradePrompt;

	/**
	 * Quota-blocked-cases buffer state — present on `quota_buffer_available`
	 * (driving the save-prompt) and `quota_fully_exhausted` (showing the
	 * "you have N of N saved" framing on upgrade-required).
	 */
	bufferState?: BufferState;

	/**
	 * ISO date string of the DSA's next billing cycle anchor. Used by
	 * the save-prompt to surface "your case will process on Dec 15."
	 * Undefined when the DSA has no active sub or anchor is unset
	 * (new subscriber edge case — copy falls back to generic
	 * "on your next billing date").
	 */
	nextCycleAt?: string | null;

	/**
	 * True when the case was successfully saved to the quota buffer
	 * (saveToBuffer was true on the request AND the server accepted).
	 * Callers route to the dashboard cases list (NOT /evaluating —
	 * no offers were computed, no animation to show).
	 */
	quotaBlocked?: boolean;

	/**
	 * Case ID — present on every successful response (normal eval AND
	 * buffer save). For buffer-saved cases the client can deep-link to
	 * the dashboard case row.
	 */
	caseId?: string;

	/** Loan amount the server saw on the request, echoed for the animation header. */
	amountRequested?: number;

	/** Tenure (years) the server saw on the request, echoed for the animation header. */
	tenureYears?: number;

	/** Offer count from the rule engine. Used by the animation completion copy. */
	offerCount?: number;
}

// ── Error message map for specific HTTP status codes ─────────────

const ERROR_MESSAGES: Record<number, string> = {
	401: 'Your session has expired. Please log in again to continue.',
	402: 'Subscription required — please subscribe to a plan to run evaluations.',
	429: 'Too many requests — please wait a moment and try again.',
	409: 'This case already exists. Please refresh and try again.',
	413: 'Form data too large — please reduce attachments and try again.',
	// 504 = Vercel gateway timeout, typically a cold-start hitting the
	// function's max-duration ceiling. Tap-retry usually succeeds because
	// the function pool is now warm. See /api/cron/keep-warm keep-warm cron.
	504: 'Server is warming up — please tap Retry. The second attempt usually completes instantly.'
};

// ── Main handler ─────────────────────────────────────────────────

/**
 * QBC UX inversion — sessionStorage key holding the pending submission
 * options. confirmAndSubmit (via submitFormForEvaluation) stashes the
 * options here + navigates to /evaluating; /evaluating reads the stash
 * + fires the API call + branches into the right view (animation /
 * save-prompt / upgrade-required / error).
 */
export const PENDING_SUBMISSION_KEY = 'qbc.pendingSubmission';

/**
 * Submit form — UX inversion path. Stashes the submission options to
 * sessionStorage and navigates to /evaluating immediately, BEFORE the
 * API call. /evaluating fires the API and branches into the right view
 * (animation on success / save-prompt on quota_buffer_available /
 * upgrade-required on quota_fully_exhausted / retry on other errors).
 *
 * Net UX win: a single spinner (the /evaluating animation) instead of
 * two (form-page spinner + /evaluating spinner). The DSA's perception is
 * "I clicked Confirm and immediately saw the evaluation start" rather
 * than "I clicked Confirm, waited, navigated, waited again."
 *
 * Pre-2026-05-30 behavior was: API call in this function, then nav to
 * /evaluating. That model still lives at `callEvaluateAndPersist` for
 * /evaluating's use.
 *
 * Returns `{ success: true }` once navigation kicks off — the actual
 * API outcome surfaces inside /evaluating, NOT to the caller. Callers
 * that need the outcome should listen on the dashboard route they end
 * up at (or query the case directly).
 */
export async function submitFormForEvaluation(options: SubmitOptions): Promise<SubmitResult> {
	if (!browser) {
		return {
			success: false,
			error: 'submitFormForEvaluation can only be called from the browser',
			code: 'SERVER_SIDE_CALL'
		};
	}
	try {
		// Generate a single idempotency key for this submission. Both
		// attempts of the silent auto-retry (handleFreshSubmission) share
		// it — the server uses it to dedupe a case insert if the first
		// attempt's function completed past the gateway timeout. Skipped
		// for edits (req.editCaseId path doesn't create a new case anyway).
		const optionsWithKey: SubmitOptions = options.editCaseId
			? options
			: {
					...options,
					idempotencyKey:
						options.idempotencyKey ??
						(typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function'
							? crypto.randomUUID()
							: `idem-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`)
				};

		// safeSessionStorage gracefully no-ops on Safari private browsing /
		// full quota / corporate browser policies that throw on raw access.
		safeSessionStorage.setItem(PENDING_SUBMISSION_KEY, JSON.stringify(optionsWithKey));
		await goto('/evaluating');
		return { success: true };
	} catch (err) {
		return {
			success: false,
			error:
				err instanceof Error
					? err.message
					: 'Navigation to evaluation page failed. Please try again.',
			code: 'NAVIGATION_FAILED'
		};
	}
}

/**
 * 2-phase submit orchestrator. Called by /evaluating after it reads the
 * stashed SubmitOptions. Internally fires:
 *
 *   Phase 1: POST /api/evaluate-and-persist  → caseId
 *   Phase 2: POST /api/cases/[caseId]/evaluate-offers  → offerCount
 *
 * The split exists so each phase runs under Vercel's 10s Hobby function
 * ceiling (phase 1 ≈ 1-3s, phase 2 ≈ 4-6s). Pre-2026-06-03 this was a
 * single call hitting 8-12s on cold start and 504-ing.
 *
 * Phase 2 is skipped when:
 *   - Phase 1 returns a 4xx/5xx (no case was created OR creation failed)
 *   - Phase 1 returns `quotaBlocked: true` (no offers for buffered cases)
 *
 * Security invariant: phase 2 takes ONLY a caseId from URL — never a
 * client-supplied payload. The server reads the persisted FormSnapshot
 * for that case. This client never sends formState to phase 2.
 *
 * The caller's SubmitResult interface is unchanged from the pre-split
 * shape: success + caseId + offerCount + amountRequested + tenureYears
 * (+ the 402 quota fields). The fact that we made two HTTP calls is
 * internal to this function. Pre-2026-05-30 this logic lived inside
 * submitFormForEvaluation itself; the UX inversion split them apart so
 * /evaluating can render the API outcome inline.
 */
export async function callEvaluateAndPersist(options: SubmitOptions): Promise<SubmitResult> {
	const {
		loanType,
		loanDisplayName,
		formStateJson,
		relationships,
		editCaseId,
		saveToBuffer,
		idempotencyKey
	} = options;

	try {
		// ── 1. Call the evaluate-and-persist API ──
		const evalResponse = await secureFetch('/api/evaluate-and-persist', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({
				loanType,
				loanDisplayName,
				formState: formStateJson,
				relationships,
				editCaseId: editCaseId || undefined,
				// QBC: opt-in to the buffer save when the DSA confirmed via
				// the save-prompt. Server only honors this when the case-limit
				// gate would otherwise reject — for under-quota submissions
				// it's a no-op (normal flow).
				...(saveToBuffer && { save_to_buffer: true }),
				// Idempotency: same UUID on both attempts of the silent
				// auto-retry. Server dedupes new-case inserts within a 10-min
				// window so the retry doesn't produce a duplicate when the
				// first attempt's function completed past the gateway timeout.
				...(idempotencyKey && { idempotency_key: idempotencyKey })
			})
		});

		// ── 2. Handle non-OK responses with specific error messages ──
		if (!evalResponse.ok) {
			const statusCode = evalResponse.status;

			// 401 = session is genuinely dead by the time we got here. secureFetch's
			// 401-retry already tried the refresh-token round-trip and that also
			// failed (otherwise the original POST would have succeeded on retry).
			// Surface the friendlier "session expired" message AND redirect to
			// /login with `?redirect=<current-path>` so the user can re-auth and
			// land back on the same submit step. Their typed form data is
			// auto-persisted by formState's localStorage adapter, so re-clicking
			// "Show Offers" after login picks up exactly where they left off.
			//
			// Pre-fix UX: the raw server "Authentication required" string landed
			// in submitError as a dead-end inline message with no recourse
			// (user-reported 2026-05-27 on Home Loan Pre-Sanction Profile).
			if (statusCode === 401 && browser) {
				const returnTo = window.location.pathname + window.location.search;
				await goto(`/login?redirect=${encodeURIComponent(returnTo)}`);
				return {
					success: false,
					error: ERROR_MESSAGES[401],
					code: 'SESSION_EXPIRED'
				};
			}

			// Try to extract the server's specific error message first
			// (the server may return different 402 errors: subscription vs case limit)
			const errorBody = await evalResponse.json().catch(() => ({}) as Record<string, unknown>);
			const serverMessage = errorBody.error as string | undefined;
			const serverCode = errorBody.code as string | undefined;

			// Use server message if available, otherwise fall back to status-based defaults
			const errorMessage =
				serverMessage || ERROR_MESSAGES[statusCode] || 'Evaluation failed. Please try again.';

			// QBC (S1): surface structured upgrade prompt + buffer state for
			// the two new 402 codes. Caller branches on `code` to render
			// the appropriate modal (save-prompt for `quota_buffer_available`,
			// upgrade-required for `quota_fully_exhausted`).
			const isQuotaCode =
				statusCode === 402 &&
				(serverCode === 'quota_buffer_available' || serverCode === 'quota_fully_exhausted');
			const upgradePromptRaw = errorBody.upgrade as Record<string, unknown> | undefined;
			const bufferRaw = errorBody.buffer as Record<string, unknown> | undefined;
			const upgradePrompt: UpgradePrompt | undefined =
				isQuotaCode && upgradePromptRaw
					? {
							plan_id: String(upgradePromptRaw.plan_id ?? ''),
							plan_name: String(upgradePromptRaw.plan_name ?? ''),
							plan_limit: Number(upgradePromptRaw.plan_limit ?? 0),
							current_count: Number(upgradePromptRaw.current_count ?? 0),
							recommended_plan: String(upgradePromptRaw.recommended_plan ?? ''),
							recommended_plan_name: String(upgradePromptRaw.recommended_plan_name ?? ''),
							recommended_plan_limit:
								upgradePromptRaw.recommended_plan_limit === null
									? null
									: Number(upgradePromptRaw.recommended_plan_limit ?? 0)
						}
					: undefined;
			const bufferState: BufferState | undefined =
				isQuotaCode && bufferRaw
					? {
							used: Number(bufferRaw.used ?? 0),
							capacity: Number(bufferRaw.capacity ?? 0),
							remaining: Number(bufferRaw.remaining ?? 0)
						}
					: undefined;
			const nextCycleAt =
				isQuotaCode && typeof errorBody.next_cycle_at === 'string'
					? errorBody.next_cycle_at
					: undefined;

			return {
				success: false,
				error: errorMessage,
				code: serverCode || `HTTP_${statusCode}`,
				...(upgradePrompt && { upgradePrompt }),
				...(bufferState && { bufferState }),
				...(nextCycleAt !== undefined && { nextCycleAt })
			};
		}

		// ── 3. Parse successful response ──
		const evalResult = await evalResponse.json();

		if (!evalResult.success) {
			return {
				success: false,
				error: evalResult.error || 'Evaluation failed. Please try again.',
				code: evalResult.code
			};
		}

		const {
			caseId,
			amountRequested,
			tenureYears,
			quota_blocked,
			needs_evaluation
		} = evalResult.data as {
			caseId: string;
			amountRequested?: number;
			tenureYears?: number;
			quota_blocked?: boolean;
			needs_evaluation?: boolean;
		};

		// QBC: blocked cases don't get an animation — /evaluating reads the
		// quotaBlocked flag and renders the "saved to buffer" view + navs
		// to the dashboard cases list. Phase 2 skipped (no offers compute
		// for buffered cases; the auto-unblock cron handles them later).
		if (quota_blocked || needs_evaluation === false) {
			return { success: true, quotaBlocked: true, caseId };
		}

		// ── PHASE 2: evaluate offers ────────────────────────────────────────
		// Phase 1 created the case + FormSnapshot in 1-3s; phase 2 runs the
		// rule engine + persists results in 4-6s. Each phase fits well under
		// Vercel's 10s Hobby ceiling separately. Security invariant: phase 2
		// takes ONLY caseId from URL — never a request body — so the server
		// reads the FormSnapshot we just persisted instead of trusting any
		// client-supplied payload.
		const phase2Response = await secureFetch(
			`/api/cases/${encodeURIComponent(caseId)}/evaluate-offers`,
			{
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: '{}' // empty body by design; caseId is in the URL
			}
		);

		if (!phase2Response.ok) {
			// Phase 1 succeeded; phase 2 failed. The case EXISTS but has no
			// LenderResultsSnapshot yet. Surface a recoverable error — the
			// caller can navigate the DSA to the case-detail page where a
			// "Re-evaluate offers" affordance can retry phase 2.
			const phase2Body = await phase2Response
				.json()
				.catch(() => ({}) as Record<string, unknown>);
			const phase2Code =
				(phase2Body.code as string | undefined) || `HTTP_${phase2Response.status}`;
			const phase2Msg =
				(phase2Body.error as string | undefined) ||
				ERROR_MESSAGES[phase2Response.status] ||
				'Offer evaluation failed. Your case was saved; please try again.';

			return {
				success: false,
				error: phase2Msg,
				code: phase2Code,
				caseId, // crucial: caller knows the case EXISTS even though phase 2 failed
				amountRequested,
				tenureYears
			};
		}

		const phase2Result = await phase2Response.json();
		const phase2Data = (phase2Result.data ?? {}) as {
			caseId?: string;
			offerCount?: number;
			cached?: boolean;
		};

		// Fire-and-forget eligibility sync (non-blocking). Best-effort: if it
		// fails the case still exists and can be synced later.
		secureFetch(`/api/cases/${caseId}/eligibility-sync`, {
			method: 'POST'
		}).catch(() => {
			/* intentional: best-effort */
		});

		return {
			success: true,
			caseId,
			amountRequested,
			tenureYears,
			offerCount: phase2Data.offerCount ?? 0
		};
	} catch (networkError) {
		// Network error (offline, DNS failure, etc.)
		return {
			success: false,
			error:
				networkError instanceof Error
					? networkError.message
					: 'Network error — please check your connection and try again.',
			code: 'NETWORK_ERROR'
		};
	}
}
