import jsPDF from "jspdf";

interface AssessmentResult {
  id: string;
  title?: string;
  conditions: any;
  riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  legalStanding: string;
  urgency: "LOW" | "MEDIUM" | "HIGH" | "IMMEDIATE";
  solutions: string[];
  timeframe: string;
  estimatedCost: string;
  keyRisks: string[];
  nextSteps: string[];
}

// Helper function to convert an image URL to Base64
const getImageBase64 = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "Anonymous";
    img.src = url;
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx?.drawImage(img, 0, 0);
      const dataURL = canvas.toDataURL("image/png");
      resolve(dataURL);
    };
    img.onerror = () => reject(new Error("Failed to load image"));
  });
};

export const generatePDFReport = async (
  assessment: AssessmentResult,
  userInfo?: any
): Promise<void> => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = {
    left: 15,
    right: 15,
    top: 15,
    bottom: 25
  };
  const lineHeight = 6;
  const fontSize = 10;
  const font = "helvetica";
  let currentPage = 1;
  let yPosition = margin.top;

  // Define currentDate early
  const currentDate = new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  // Helper function to normalize text (remove extra spaces, handle special chars)
  const normalizeText = (text: string): string => {
    return text.replace(/\s+/g, " ").trim();
  };

  // Helper function to calculate text height
  const getTextHeight = (text: string, maxWidth: number): number => {
    doc.setFont(font, "normal");
    doc.setFontSize(fontSize);
    const normalizedText = normalizeText(text);
    const lines = doc.splitTextToSize(normalizedText || "Not specified", maxWidth);
    return lines.length * lineHeight;
  };

  // Helper function to add text with word wrapping
  const addWrappedText = (
    text: string,
    x: number,
    y: number,
    maxWidth: number
  ): number => {
    doc.setFont(font, "normal");
    doc.setFontSize(fontSize);
    const normalizedText = normalizeText(text);
    const lines = doc.splitTextToSize(normalizedText || "Not specified", maxWidth);
    doc.text(lines, x, y);
    return y + lines.length * lineHeight;
  };

  // Helper function to check and add new page
  const checkNewPage = (requiredSpace: number): number => {
    if (yPosition + requiredSpace > pageHeight - margin.bottom) {
      doc.addPage();
      currentPage++;
      addFooter();
      return margin.top;
    }
    return yPosition;
  };

  // Helper function to add section header
  const addSectionHeader = (title: string, y: number): number => {
    doc.setFont(font, "bold");
    doc.setFontSize(fontSize);
    doc.setTextColor(51, 65, 85);
    doc.text(title.toUpperCase(), margin.left, y);
    doc.setFont(font, "normal");
    doc.setTextColor(0, 0, 0);
    return y + lineHeight * 1.5;
  };

  // Helper function to add footer
  const addFooter = () => {
    const footerY = pageHeight - margin.bottom + 5;
    doc.setFillColor(255, 204, 0);
    doc.rect(0, footerY , pageWidth, 20, "F");
    
    doc.setFont(font, "bold");
    doc.setFontSize(fontSize);
    doc.setTextColor(0, 0, 0);
    doc.text("Digital DSA", margin.left, footerY + 7);
    
    doc.setFont(font, "normal");
    doc.setFontSize(8);
    doc.text(
      "www.digitaldsa.com  ",
      margin.left,
      footerY + 15
    );
    doc.text(
      `Page ${currentPage} of ${doc.getNumberOfPages()}`,
      pageWidth - margin.right - 30,
      footerY + 12
    );
  };

  // Header
  doc.setFillColor(255, 204, 0);
  doc.rect(0, 0, pageWidth, 40, "F");

  // Company logo
  const logoUrl = "/logo/newLogo.png"; // Replace with your logo URL or file path
  let logoBase64: string;
  try {
    logoBase64 = await getImageBase64(logoUrl);
    doc.addImage(logoBase64, "PNG", margin.left, 12, 12, 20); // Adjust format (PNG/JPEG) and size as needed
  } catch (error) {
    console.error("Error loading logo:", error);
    // Fallback to placeholder if logo fails to load
    doc.setFillColor(0, 0, 0);
    doc.rect(margin.left, 10, 20, 20, "F");
    doc.setTextColor(255, 204, 0);
    doc.setFontSize(fontSize);
    doc.text("🏠", margin.left + 6, 24);
  }

  // Title
  doc.setTextColor(0, 0, 0);
  doc.setFont(font, "bold");
  doc.setFontSize(fontSize);
  doc.text("Property Risk Assessment", margin.left + 20, 20);
  doc.setFont(font, "normal");
  doc.text("Generated by Digital Dsa", margin.left + 20, 25);
  yPosition = 50;

  // Report Details
  yPosition = checkNewPage(30);
  const reportDetailsText = `Generated: ${currentDate}\nReport ID: ${assessment.id}`;
  const reportDetailsHeight = getTextHeight(reportDetailsText, pageWidth - margin.left - margin.right) + 10;
  doc.setFillColor(248, 250, 252);
  doc.rect(margin.left - 5, yPosition - 5, pageWidth - margin.left - margin.right + 10, reportDetailsHeight, "F");
  
  yPosition = addSectionHeader("Report Details", yPosition);
  doc.text(`Generated: ${currentDate}`, margin.left, yPosition);
  doc.text(`Report ID: ${assessment.id}`, pageWidth - margin.right - 60, yPosition);
  yPosition += reportDetailsHeight;

  // Legal Standing
  yPosition = checkNewPage(40);
  const legalStandingHeight = getTextHeight(assessment.legalStanding, pageWidth - margin.left - margin.right) + 10;
  doc.setFillColor(249, 250, 251);
  doc.roundedRect(margin.left - 5, yPosition - 5, pageWidth - margin.left - margin.right + 10, legalStandingHeight,3,3, "F");
  
  yPosition = addSectionHeader("Legal Standing", yPosition);
  yPosition = addWrappedText(assessment.legalStanding,
    margin.left,
    yPosition,
    pageWidth - margin.left - margin.right
  );
  yPosition += lineHeight;

  // Timeframe and Estimated Cost (Two-column layout)
  yPosition = checkNewPage(50);
  const halfWidth = (pageWidth - margin.left - margin.right - 10) / 2;
  
  // Timeframe
  const timeframeHeight = getTextHeight(assessment.timeframe, halfWidth - 5) + 15; // Add padding
  doc.setFillColor(254, 249, 195);
  doc.roundedRect(margin.left - 5, yPosition - 5, halfWidth, timeframeHeight, 3, 3, "F");
  const timeframeStartY = yPosition;
  yPosition = addSectionHeader("Timeframe", yPosition);
  const timeframeEndY = addWrappedText(
    assessment.timeframe,
    margin.left,
    yPosition,
    halfWidth - 5
  );

  // Estimated Cost
  const costHeaderHeight = lineHeight * 1.5; // Height of "EST. COST" header
  const costTextHeight = getTextHeight(assessment.estimatedCost, halfWidth - 5);
  const costHeight = costHeaderHeight + costTextHeight +5; // Include header and padding
  doc.setFillColor(220, 252, 231);
  doc.roundedRect(pageWidth / 2+8, timeframeStartY - 5, halfWidth, costHeight, 3, 3, "F");
  const costStartY = timeframeStartY; // Align with Timeframe's starting Y
  doc.setFont(font, "bold");
  doc.setFontSize(fontSize);
  doc.setTextColor(51, 65, 85);
  doc.text("EST. COST (in Rupees)", pageWidth / 2 + 13, costStartY);
  doc.setFont(font, "normal");
  doc.setTextColor(0, 0, 0);
  const costEndY = addWrappedText(
    assessment.estimatedCost,
    pageWidth / 2 +13,
    costStartY + costHeaderHeight,
    halfWidth - 5
  );
  yPosition = Math.max(timeframeEndY, costEndY) + lineHeight * 2;

  // Key Risks
  yPosition = checkNewPage(60);
  const risksHeight = (assessment.keyRisks || []).reduce((total, risk) => 
    total + getTextHeight(risk, pageWidth - margin.left - margin.right - 10) + 3, 10
  );
  doc.setFillColor(254, 242, 242);
  doc.roundedRect(margin.left - 5, yPosition - 5, pageWidth - margin.left - margin.right + 10, risksHeight,3, 3	, "F");
  yPosition = addSectionHeader("Key Risks Identified", yPosition);

  (assessment.keyRisks || []).forEach((risk, index) => {
    yPosition = checkNewPage(20);
    doc.setFillColor(239, 68, 68);
    doc.circle(margin.left, yPosition - 2, 2, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont(font, "bold");
    doc.text(`${index + 1}`, margin.left - 0.8, yPosition - 0.5);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(fontSize);
    doc.setFont(font, "normal");
    yPosition = addWrappedText(
      risk,
      margin.left + 8,
      yPosition,
      pageWidth - margin.left - margin.right - 10
    );
    yPosition += 3;
  });
  yPosition += lineHeight;

  // Next Steps
  yPosition = checkNewPage(60);
  const nextStepsHeight = (assessment.nextSteps || []).reduce((total, step) => 
    total + lineHeight + 2, 10
  );
  doc.setFillColor(225, 245, 225);
  doc.roundedRect(margin.left - 5, yPosition - 5, pageWidth - margin.left - margin.right + 10, nextStepsHeight, 3, 3, "F");
  yPosition = addSectionHeader("Immediate Next Steps", yPosition);

  (assessment.nextSteps || []).forEach((step, index) => {
    yPosition = checkNewPage(15);
    doc.setFillColor(0, 128, 0);
    doc.circle(margin.left, yPosition - 2, 2, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text(`${index + 1}`, margin.left - 0.8, yPosition - 0.5);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(fontSize);
    doc.text(step, margin.left + 8, yPosition);
    yPosition += lineHeight + 2;
  });
  yPosition += lineHeight;

  // Recommended Solutions
  yPosition = checkNewPage(60);
  const solutionsHeight = (assessment.solutions || []).reduce((total, solution) => 
    total + lineHeight + 2, 10
  );
  doc.setFillColor(255, 251, 235);
  doc.roundedRect(margin.left - 5, yPosition - 5, pageWidth - margin.left - margin.right + 10, solutionsHeight, 3, 3, "F");
  yPosition = addSectionHeader("Recommended Solutions", yPosition);

  (assessment.solutions || []).forEach((solution, index) => {
    yPosition = checkNewPage(15);
    doc.setFillColor(0, 128, 0);
    doc.circle(margin.left, yPosition - 2, 2, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text(`${index + 1}`, margin.left - 0.8, yPosition - 0.5);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(fontSize);
    doc.text(solution, margin.left + 8, yPosition);
    yPosition += lineHeight + 2;
  });

  // Add footer
  addFooter();

  // Generate filename
  const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, "-");
  const filename = `PropertyGuard_Risk_Assessment_${timestamp}.pdf`;

  // Save the PDF
  try {
    doc.save(filename);
  } catch (error) {
    console.error("Error generating PDF:", error);
    throw new Error("Failed to generate PDF report");
  }
};


// Enhanced Helper functions
const getDocumentTypeLabel = (type: string): string => {
  const labels: Record<string, string> = {
    registered_sale_deed: "Registered Sale Deed",
    gpa_agreement: "GPA/Agreement to Sell",
    builder_buyer_agreement: "Builder-Buyer Agreement",
    inherited: "Inherited Property",
    mutation_only: "Only Mutation/Patta",
    other: "Other Documents",
  };
  return labels[type] || type;
};

const getLegalOwnerLabel = (owner: string): string => {
  const labels: Record<string, string> = {
    self: "Myself",
    parent_spouse: "Parent/Spouse",
    seller_name: "Seller's Name",
    other_family: "Other Family Member",
  };
  return labels[owner] || owner;
};

const getIntentLabel = (intent: string): string => {
  const labels: Record<string, string> = {
    check_status: "Check ownership status",
    regularize: "Regularize ownership",
    sell: "Sell the property",
    transfer: "Transfer to family",
    get_advice: "Get legal advice",
  };
  return labels[intent] || intent;
};
