import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';
import fs from 'fs';
import path from 'path';

// Synchronously delete unused/unwanted directories and files for the website-only version
const cleanUpPaths = [
	'src/routes/dashboard',
	'src/routes/dsa-onboarding',
	'src/routes/rm-onboarding',
	'src/routes/(auth)',
	'src/routes/(main)/(loans)/check-offers',
	'src/routes/(tools)',
	'src/lib/tools',
	'src/lib/components/tools',
	'src/routes/api/cron',
	'src/routes/api/onboarding',
	'src/routes/api/evaluate-and-persist',
	'src/routes/api/billing',
	'src/routes/api/crm-lenders',
	'src/routes/api/sources',
	'src/routes/api/communication',
	'src/routes/api/notifications',
	'src/routes/api/pms',
	'src/routes/api/qa',
	'src/routes/api/razorpay',
	'src/routes/api/security',
	'src/routes/api/set-role',
	'src/routes/api/share-link',
	'src/routes/api/surveys',
	'src/routes/api/tasks',
	'src/routes/api/team',
	'src/routes/api/test',
	'src/routes/api/update-coins',
	'src/routes/api/get-coins',
	'src/routes/api/upload',
	'src/routes/api/upload-photo',
	'src/routes/api/user',
	'src/routes/api/users',
	'src/routes/api/walkthrough',
	'src/routes/api/nbfc-capabilities',
	'src/routes/api/pincodes',
	'src/routes/api/account',
	'src/routes/api/auth',
	'src/routes/api/disclaimer',
	'src/lib/ruleEngine',
	'src/lib/components/onboarding',
	'src/lib/components/policy',
	'src/lib/components/evaluation',
	'src/lib/components/relationship-capture',
	'src/lib/components/walkthrough',
	'src/lib/components/billing',
	'src/lib/components/account',
	'src/lib/components/auth',
	'src/lib/server/account',
	'src/lib/server/billing',
	'src/lib/server/formGuard.ts',
	// Wizard components directly under src/lib/components/
	'src/lib/components/AddApplicant.svelte',
	'src/lib/components/AddApplicantBusiness.svelte',
	'src/lib/components/AddApplicantPersonal.svelte',
	'src/lib/components/AddApplicantProfessional.svelte',
	'src/lib/components/ApplicantCard.svelte',
	'src/lib/components/ApplicantFormCard.svelte',
	'src/lib/components/ApplicantFormSecured.svelte',
	'src/lib/components/ApplicantFormUnsecured.svelte',
	'src/lib/components/ApplicantKeepPickerModal.svelte',
	'src/lib/components/ApplicantModal.svelte',
	'src/lib/components/ApplicantProfilePage.svelte',
	'src/lib/components/ApplicantRow.svelte',
	'src/lib/components/ApplicantSelect.svelte',
	'src/lib/components/ApplicantSummaryTable.svelte',
	'src/lib/components/BasicInfoUnsecureLoan.svelte',
	'src/lib/components/BtStructurePanel.svelte',
	'src/lib/components/BusinessRunnerPage.svelte',
	'src/lib/components/Company.svelte',
	'src/lib/components/CompanyBusinessProfile.svelte',
	'src/lib/components/CompanyCharacterTab.svelte',
	'src/lib/components/CompanyDeleteDialog.svelte',
	'src/lib/components/CompanyDetails.svelte',
	'src/lib/components/CompanyFinancials.svelte',
	'src/lib/components/CompanyIncomeTab.svelte',
	'src/lib/components/ContradictionWarningModal.svelte',
	'src/lib/components/CreditScoreSection.svelte',
	'src/lib/components/CrossFieldWarningBanner.svelte',
	'src/lib/components/CustomIncomeTable.svelte',
	'src/lib/components/DirectorCards.svelte',
	'src/lib/components/DirectorCountPicker.svelte',
	'src/lib/components/DirectorFormModal.svelte',
	'src/lib/components/DirectorRemovePickerModal.svelte',
	'src/lib/components/Directors.svelte',
	'src/lib/components/DocumentUploadSection.svelte',
	'src/lib/components/DynamicField.svelte',
	'src/lib/components/ExistingLoanDetails.svelte',
	'src/lib/components/GPAOfNriApplicant.svelte',
	'src/lib/components/IncomeModalContent.svelte',
	'src/lib/components/IncomePageNew.svelte',
	'src/lib/components/IncomeProfileSelector.svelte',
	'src/lib/components/IncomeSourceEntries.svelte',
	'src/lib/components/IncomeSourceForm.svelte',
	'src/lib/components/IncomeTabContent.svelte',
	'src/lib/components/InterestRateTextField.svelte',
	'src/lib/components/MonthYearModal.svelte',
	'src/lib/components/ObligationCapture.svelte',
	'src/lib/components/Pensioner.svelte',
	'src/lib/components/ProfileTabContent.svelte',
	'src/lib/components/QuestionRadioForm.svelte',
	'src/lib/components/QuestionRenderer.svelte',
	'src/lib/components/RelationShip.svelte',
	'src/lib/components/RelationTable.svelte',
	'src/lib/components/RestoreApplicantModal.svelte',
	'src/lib/components/SalariedPerson.svelte',
	'src/lib/components/SameCompanyPromptModal.svelte',
	'src/lib/components/SelfEmploymentOther.svelte',
	'src/lib/components/SelfEmploymentProfessional.svelte',
	'src/lib/components/YesNoButtons.svelte',
	'src/lib/components/applicantFormManager.svelte.ts',
	'src/lib/components/obligationCaptureLogic.ts',
	// Wizard Configs
	'src/lib/config/homeLoan',
	'src/lib/config/lapLoan',
	'src/lib/config/plotLoan',
	'src/lib/config/personalLoan',
	'src/lib/config/businessLoan',
	'src/lib/config/professionalLoan',
	'src/lib/config/wizardSections',
	'src/lib/config/wizardConfigs',
	'src/lib/config/incomeProfiles',
	'src/lib/config/companyProfile',
	'src/lib/config/deepBusinessProfile',
	'src/lib/config/applicantQuestions.ts',
	'src/lib/config/formSchema.json',
	'src/lib/config/obligation.json',
	'src/lib/config/billing.ts',
	'src/lib/config/billingSellerInfo.ts',
	'src/lib/config/permissions.ts',
	'src/lib/config/accessControl.ts',
	'src/lib/state/form.svelte.ts',
	'src/lib/testing'
];

for (const targetPath of cleanUpPaths) {
	const absolutePath = path.resolve(targetPath);
	if (fs.existsSync(absolutePath)) {
		try {
			fs.rmSync(absolutePath, { recursive: true, force: true });
			console.log(`[CleanUp] Successfully deleted: ${targetPath}`);
		} catch (err) {
			console.error(`[CleanUp] Failed to delete ${targetPath}:`, err);
		}
	}
}

export default defineConfig({
	plugins: [sveltekit(), tailwindcss()]
});
