/**
 * POST /api/public/consent-revoke — Customer self-revocation
 * ══════════════════════════════════════════════════════════════════
 * UNAUTHENTICATED public endpoint. The customer's case PDF carries a
 * link `https://app.digitaldsa.com/consent/revoke?token={revocation_token}`.
 * Clicking the link lands them on a public page, which calls this
 * endpoint with the token in the body.
 *
 * Auth model: the HMAC `revocation_token` IS the authentication. No
 * account, no OTP, no login. The token is generated at vault entry
 * creation, embedded in the PDF, and never shared elsewhere.
 *
 * Rate-limited per IP to slow down anyone trying to brute-force tokens.
 *
 * Spec: docs/specs/DATA-2-CONSENTED-VAULT-SPEC.md §9.
 * ══════════════════════════════════════════════════════════════════
 */

import type { RequestHandler } from './$types';
import { z } from 'zod';
import { OutreachVault } from '$lib/database/mongo.js';
import { apiOk, apiError, apiServerError, apiValidationError, parseJsonBody } from '$lib/server/apiResponse.js';
import { rateLimit } from '$lib/server/rateLimiter.js';
import { verifyRevocationToken } from '$lib/server/data2/revocationToken.js';
import { mobileHashForToken } from '$lib/server/data2/mobileHash.js';
import { decryptValue } from '$lib/server/csfle/index.js';
import { MongoClientInstance } from '$lib/database/mongo.js';
import type { Binary } from 'mongodb';
import logger from '$lib/server/logger.js';

const GRACE_PERIOD_DAYS = 90;

const requestSchema = z.object({
	token: z.string().min(32).max(64)
});

export const POST: RequestHandler = async ({ request, getClientAddress }) => {
	// Tight rate limit — this endpoint is unauthenticated and is the
	// natural target for a token brute-force attempt. 20 attempts/hour
	// per IP gives a real customer plenty of room while making forgery
	// computationally and rate-wise infeasible.
	const ip = getClientAddress();
	const limited = await rateLimit(ip, {
		identifier: `consent-revoke:${ip}`,
		maxRequests: 20,
		windowMs: 60 * 60 * 1000
	});
	if (limited) {
		return apiError('Too many revocation attempts. Please wait before trying again.', 429);
	}

	const jsonParsed = await parseJsonBody<Record<string, unknown>>(request);
	if (!jsonParsed.ok) return jsonParsed.response;

	const parsed = requestSchema.safeParse(jsonParsed.data);
	if (!parsed.success) {
		return apiValidationError('Validation failed', parsed.error.flatten());
	}

	const { token } = parsed.data;

	try {
		// Look up by token — unique index on revocation_token guarantees
		// at most one match. We don't reveal whether the token was wrong
		// vs the entry was already revoked vs grace-period expired — all
		// failure modes return the same generic message.
		const entry = await OutreachVault.findOne({ revocation_token: token });
		if (!entry) {
			// Constant-time-ish: still pay the rate-limit cost above so
			// guessing a token has the same wall-clock as a real revoke.
			return apiError('Invalid or expired revocation link.', 400);
		}

		if (entry.consent_status !== 'active') {
			// Already revoked or expired — return success-ish to keep the
			// UX simple for the customer ("your consent is already withdrawn").
			return apiOk({
				already_revoked: true,
				revoked_at: entry.revoked_at?.toISOString(),
				message:
					'Consent has already been withdrawn for this entry. No further action needed.'
			});
		}

		// Recompute the expected token from the entry's fields and verify
		// in constant time. Belt + suspenders: even though we found the
		// entry by token equality (which Mongo's unique index already
		// proved), the HMAC verify guarantees the token was generated by
		// our system and not crafted from leaked _id + dsa_id values.
		const plaintextMobile = await decryptValue<string>(
			MongoClientInstance,
			entry.mobile as unknown as Binary
		);
		const expectedInputs = {
			vault_entry_id: entry._id!.toString(),
			dsa_id: entry.dsa_id.toString(),
			mobile_hash: mobileHashForToken(plaintextMobile)
		};
		if (!verifyRevocationToken(token, expectedInputs)) {
			// Should be impossible given the findOne match, but defensive.
			logger.warn(
				{ entry_id: entry._id?.toString() },
				'DATA-2: revocation token matched by lookup but HMAC verify failed'
			);
			return apiError('Invalid or expired revocation link.', 400);
		}

		const now = new Date();
		const graceEnd = new Date(now);
		graceEnd.setDate(graceEnd.getDate() + GRACE_PERIOD_DAYS);

		await OutreachVault.updateOne(
			{ _id: entry._id, consent_status: 'active' },
			{
				$set: {
					consent_status: 'revoked',
					revoked_at: now,
					revoked_by: 'customer_self',
					grace_period_ends_at: graceEnd,
					updated_at: now
				}
			}
		);

		logger.info(
			{
				vault_entry_id: entry._id?.toString(),
				dsa_id: entry.dsa_id.toString(),
				revoked_by: 'customer_self',
				ip_redacted: '***',
				grace_period_ends_at: graceEnd.toISOString()
			},
			'DATA-2: vault entry revoked by customer'
		);

		return apiOk({
			already_revoked: false,
			revoked_at: now.toISOString(),
			message:
				'Your consent has been withdrawn. The DSA will no longer contact you for BT/DC/top-up offers.'
		});
	} catch (err) {
		return apiServerError(err, 'Failed to process revocation');
	}
};
