import type { RawSchemaQuestion } from '../../types.js';
import {
	q2_ocCcAvailable,
	q3_municipalApproval
	// q4_isPossessionOfferedByAuthority removed — duplicate of q5_possessionCertificateStatus
} from '../propertyCondition.js';

/**
 * Authority counterparty questions for the `sellerTransaction_authority_homeLoan` page.
 *
 * Covers development authority selection (city-aware), allotment letter status,
 * allotment date, payment & dues status (merged), possession status,
 * plus RTM compliance questions (OC/CC, municipal approval, authority possession)
 * and authority-specific documentation readiness — all absorbed here since
 * AUTH flow skips the Compliance & Legal page.
 *
 * These questions apply only to direct_from_authority purchase type + New Loan.
 *
 * NOTE: Original questions use `bindsTo` (not `bindsTo_template`) because they were added
 * in a later batch after the template binding convention was established.
 *
 * Session 32: Redesigned — authority select from city, better allotment options,
 * merged payment+dues, simplified possession, showWhen cascading,
 * authority-specific doc readiness (replaces generic planned-area variant).
 */
export function getAuthorityQuestions(): RawSchemaQuestion[] {
	return [
		// ── q1: Authority Name (dynamic options from city/state) ──────
		// Options are dynamically generated by optionResolver based on the
		// selected property city/state from developmentAuthorities.json.
		// Static options below are fallbacks only (used if city is not yet set).
		{
			id: 'q1_authorityName',
			bindsTo: 'authorityName',
			contextKey: 'authorityName',
			type: 'select',
			uiGroup: 'select_fields',
			selectClass: 'mt-8 md:mt-12',
			searchBarNeeded: true,
			uiMeta: {
				placeholder: 'Select development authority',
				icon: 'landmark'
			},
			question: 'Which development authority is allotting the property?',
			options: [
				{ label: 'Military / Defence authority (e.g., Army Welfare Housing)', value: 'DEFENCE' },
				{ label: 'Other authority', value: 'OTHER' }
			],
			required: true
		},

		// ── q2: Allotment Letter Status ────────────────────────────────
		{
			id: 'q2_allotmentLetterStatus',
			bindsTo: 'allotmentLetterStatus',
			contextKey: 'allotmentLetterStatus',
			type: 'radio',
			radioClass: 'mt-8 md:mt-12',
			optionContainerClass: 'grid gap-3',
			question: 'Is the allotment letter / sanction letter available?',
			options: [
				{
					label: 'Original allotment letter in hand',
					value: 'ORIGINAL_AVAILABLE',
					icon: 'CheckCircle2'
				},
				{
					label: 'Certified copy in hand',
					value: 'COPY_AVAILABLE',
					icon: 'FileText'
				},
				{
					label: 'Allotment confirmed but letter not yet received',
					value: 'PENDING_RECEIPT',
					icon: 'Clock'
				},
				{
					label: 'No allotment letter',
					value: 'NOT_AVAILABLE',
					icon: 'Ban'
				}
			],
			required: true
		},

		// ── q3: Allotment Date ─────────────────────────────────────────
		{
			id: 'q3_allotmentDate',
			bindsTo: 'allotmentDate',
			contextKey: 'allotmentDate',
			type: 'text',
			uiType: 'monthYear',
			textFieldClass: 'mt-8 md:mt-12',
			uiGroup: 'inputNumber',
			uiMeta: {
				placeholder: 'Select month and year',
				icon: 'calendar',
				minYear: 2000
			},
			question: 'When was the property allotted?',
			required: true,
			showWhen: {
				'!=': [{ var: 'allotmentLetterStatus' }, 'NOT_AVAILABLE']
			}
		},

		// ── q4: Payment & Dues Status (merged q4 + q6) ────────────────
		{
			id: 'q4_authorityPaymentStatus',
			bindsTo: 'authorityPaymentStatus',
			contextKey: 'authorityPaymentStatus',
			type: 'radio',
			radioClass: 'mt-8 md:mt-12',
			optionContainerClass: 'grid gap-3',
			question: 'What is the payment & dues status to the authority?',
			options: [
				{
					label: 'Major installments pending',
					value: 'MAJOR_PENDING',
					icon: 'AlertTriangle'
				},
				{
					label: 'Minor dues remaining',
					value: 'MINOR_DUES',
					helperText: 'Penalties, interest, or small charges',
					icon: 'AlertCircle'
				},
				{
					label: 'Allotment received — all installments pending',
					value: 'ALL_PENDING',
					icon: 'Clock'
				},
				{
					label: 'Not sure',
					value: 'UNKNOWN',
					icon: 'HelpCircle'
				}
			],
			required: true,
			showWhen: {
				'!=': [{ var: 'allotmentLetterStatus' }, 'NOT_AVAILABLE']
			}
		},

		// ── q5: Possession Status (simplified) ─────────────────────────
		// NOTE: PropertyStage conflict info is on option helperText (client-visible
		// at all times) rather than server-evaluated warnings (which go stale
		// within a page since the server is called only on navigation).
		{
			id: 'q5_possessionCertificateStatus',
			bindsTo: 'possessionCertificateStatus',
			contextKey: 'possessionCertificateStatus',
			type: 'radio',
			radioClass: 'mt-8 md:mt-12',
			optionContainerClass: 'grid gap-3',
			question: 'Has the authority handed over possession?',
			options: [
				{
					label: 'Yes — possession letter/certificate received',
					value: 'POSSESSION_CERT_AVAILABLE',
					icon: 'CheckCircle2',
					helperText: 'Implies property is ready to move'
				},
				{
					label: 'No — possession not yet given',
					value: 'NOT_ISSUED',
					icon: 'Ban',
					helperText: 'Property may still be under construction'
				},
				{
					label: 'Not sure',
					value: 'UNKNOWN',
					icon: 'HelpCircle'
				}
			],
			required: true,
			showWhen: {
				'!=': [{ var: 'allotmentLetterStatus' }, 'NOT_AVAILABLE']
			}
		},

		// ── q7: Authority Documentation Readiness ──────────────────────
		// Replaces the generic planned-area documentation readiness (q1a)
		// with authority-specific document list.
		{
			id: 'q7_authorityDocReadiness',
			bindsTo: 'documentationReadiness',
			contextKey: 'documentationReadiness',
			type: 'radio',
			radioClass: 'mt-[1rem] md:mt-[2rem]',
			labelClass: 'text-black dark:text-white',
			optionContainerClass: 'grid gap-3',
			uiGroup: 'loan_details',
			required: true,
			question: 'Which key documents are available for the authority property?',
			description:
				"<div class='info-title'><i data-lucide='file-text' class='inline-block h-4 w-4'></i> Authority Documentation</div><div class='info-box highlight dark:text-gray-400'>Lenders require the allotment letter, payment receipts, and possession certificate at minimum. Having more documents ready speeds up processing.</div>",
			options: [
				{
					label: 'Allotment letter + payment receipts + possession certificate',
					value: 'ALL_KEY_DOCS',
					helperText: 'All primary documents available',
					uiMeta: { icon: 'Circle' },
					icon: 'CheckCircle2',
					// Possession must be available AND some payments made (not all pending)
					showWhen: {
						and: [
							{ '==': [{ var: 'possessionCertificateStatus' }, 'POSSESSION_CERT_AVAILABLE'] },
							{ '!=': [{ var: 'authorityPaymentStatus' }, 'ALL_PENDING'] }
						]
					}
				},
				{
					label: 'Allotment letter + payment receipts (no possession certificate)',
					value: 'ALLOTMENT_AND_RECEIPTS',
					helperText: 'Possession certificate pending or not issued',
					uiMeta: { icon: 'Circle' },
					icon: 'Clock',
					// No possession AND some payments made (not all pending)
					showWhen: {
						and: [
							{ in: [{ var: 'possessionCertificateStatus' }, ['NOT_ISSUED', 'UNKNOWN']] },
							{ '!=': [{ var: 'authorityPaymentStatus' }, 'ALL_PENDING'] }
						]
					}
				},
				{
					label: 'Only allotment letter available',
					value: 'ALLOTMENT_ONLY',
					helperText: 'Payment receipts not yet collected',
					uiMeta: { icon: 'Circle' },
					icon: 'FileText'
					// Always visible — allotment letter is the minimum
				},
				{
					label: 'Documents not yet collected',
					value: 'NOT_STARTED',
					uiMeta: { icon: 'Circle' },
					icon: 'FileQuestion'
					// Always visible — universal fallback
				}
			],
			showWhen: {
				'!=': [{ var: 'allotmentLetterStatus' }, 'NOT_AVAILABLE']
			}
		},

		// ── Compliance & Legal questions for AUTH flow ──────────────────
		// Absorbed here since AUTH skips the Compliance & Legal page.
		// These questions have their own showWhen gating for RTM stage, etc.
		q2_ocCcAvailable,
		q3_municipalApproval
		// Session 32: Removed q4_isPossessionOfferedByAuthority — duplicate of
		// q5_possessionCertificateStatus above (same info, q5 has better options + gates doc filtering)
	];
}
