/**
 * Team invite email (SEC-8 template D)
 * ══════════════════════════════════════════════════════════════════════
 * One of the four transactional templates committed to AWS SES on
 * 2026-06-01 as part of the production-access case 177987930900751.
 * Sent when an existing DSA invites a teammate via /api/team/invite
 * AND provides the teammate's email (the email field is optional —
 * legacy mobile-only invites still work and just don't trigger a send).
 *
 * Carries the shared 5-element footer + replyTo: support@digitaldsa.com
 * so it stays consistent with OTP, renewal-receipt, and dunning sends.
 * ══════════════════════════════════════════════════════════════════════
 */

import { sendEmail, type EmailResult } from '$lib/server/email';
import { PUBLIC_APP_BASE_URL } from '$lib/config/publicAppUrl';
import { escapeHtml } from '$lib/utils/sanitize';
import {
	buildTransactionalFooterHtml,
	buildTransactionalFooterText,
	SUPPORT_EMAIL
} from './footer';
import logger from '$lib/server/logger';

const ROLE_LABELS: Record<string, string> = {
	admin: 'Admin',
	data_entry: 'Data Entry',
	viewer: 'Viewer',
	field_agent: 'Field Agent'
};

export interface TeamInviteEmailArgs {
	/** Invitee's email — the recipient. Required. */
	to: string;
	/** Display name of the inviting DSA (the team owner). */
	inviterName: string;
	/** Display name of the invitee (what the inviter typed in the form). */
	inviteeName: string;
	/** 6-character invite code generated by /api/team/invite. */
	inviteCode: string;
	/** Team role assigned to the invitee. */
	teamRole: string;
}

/**
 * Send the team-invite notification. Best-effort: on send failure the
 * caller continues with the dashboard-code-only flow so the inviter
 * isn't blocked. Result is logged either way.
 */
export async function sendTeamInviteEmail(args: TeamInviteEmailArgs): Promise<EmailResult> {
	const { to, inviterName, inviteeName, inviteCode, teamRole } = args;

	const inviterSafe = escapeHtml(inviterName || 'A DigitalDSA user');
	const inviteeSafe = escapeHtml(inviteeName || 'there');
	const codeSafe = escapeHtml(inviteCode);
	const roleLabelSafe = escapeHtml(ROLE_LABELS[teamRole] ?? teamRole);
	const joinUrl = `${PUBLIC_APP_BASE_URL}/team-invite/${encodeURIComponent(inviteCode)}`;

	const subject = `${inviterName || 'A teammate'} invited you to a DigitalDSA team`;

	const html = `<!DOCTYPE html>
<html><body style="font-family: system-ui, sans-serif; line-height: 1.5; max-width: 560px; margin: 0 auto; padding: 24px;">
<h2 style="color: #111;">You've been invited to a DigitalDSA team</h2>
<p>Hi ${inviteeSafe},</p>
<p><strong>${inviterSafe}</strong> has invited you to join their DigitalDSA team as <strong>${roleLabelSafe}</strong>.</p>
<p style="margin: 28px 0;">
  <a href="${joinUrl}" style="display: inline-block; background: #cb997e; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: 600;">Accept invite</a>
</p>
<p style="color: #4b5563; font-size: 14px;">If the button doesn't work, sign in to DigitalDSA with your mobile number and enter this invite code:</p>
<p style="background: #f3f4f6; padding: 12px 16px; border-radius: 6px; font-family: monospace; font-size: 20px; font-weight: 700; letter-spacing: 4px; text-align: center; color: #111;">${codeSafe}</p>
<p style="color: #6b7280; font-size: 13px;">If you weren't expecting this, you can ignore the email — the invite expires the next time the team owner refreshes it.</p>
${buildTransactionalFooterHtml({ recipientEmail: to })}
</body></html>`;

	const text = `You've been invited to a DigitalDSA team

Hi ${inviteeName || 'there'},

${inviterName || 'A teammate'} has invited you to join their DigitalDSA team as ${ROLE_LABELS[teamRole] ?? teamRole}.

Accept invite: ${joinUrl}

Or sign in to DigitalDSA with your mobile number and enter the invite code:

  ${inviteCode}

If you weren't expecting this, you can ignore the email — the invite expires the next time the team owner refreshes it.${buildTransactionalFooterText({ recipientEmail: to })}`;

	const result = await sendEmail({
		to,
		subject,
		html,
		text,
		replyTo: SUPPORT_EMAIL
	});

	if (!result.success) {
		logger.warn(
			{ err: result.error, invite_code: inviteCode },
			'team invite email: send failed (non-fatal — dashboard code is the source of truth)'
		);
	}
	return result;
}
