/**
 * SEC-10 conflict-detection gate for /api/auth/check-dsa.
 * ────────────────────────────────────────────────────────────────────────────
 * Single entry point that all 6 user-resolution branches in check-dsa call
 * AFTER user lookup, BEFORE token issuance. Keeps the branching code in
 * check-dsa short (one helper call instead of 20 inline lines × 6 branches).
 *
 * The flow:
 *   1. Query Sessions for active rows belonging to the resolved user.
 *   2. Run detectConflict against the incoming fingerprints.
 *   3. On a 'modal' verdict, emit telemetry (`session.conflict_detected`).
 *   4. Branch on the env flag:
 *        - SESSION_ENFORCEMENT_KICK_ENABLED='true'  → return {kind:'conflict'}
 *          with the session_conflict response body. Caller MUST return it
 *          immediately and skip token issuance / cookies / recordSession.
 *        - Else (soak mode)                         → return {kind:'proceed'}.
 *          Caller continues the normal login flow. Telemetry alone tells
 *          the admin dashboard how many users would have been kicked.
 *
 * The tokenId is pre-generated by the caller (hoisted to the top of the
 * check-dsa handler) so the same value lands in:
 *   - the pending-login-token (if conflict),  OR
 *   - the access + refresh JWTs + activeTokenIds + recordSession row (if no
 *     conflict).
 * One UUID per login attempt — no separate "pending" vs "issued" ID.
 *
 * Spec: docs/specs/SINGLE-SESSION-ENFORCEMENT-SPEC.md §4 + §9 Commit B
 * ADR : docs/adr/0028-single-session-enforcement.md
 */

import type { ObjectId } from 'mongodb';
import { Sessions } from '$lib/database/mongo';
import logger from '$lib/server/logger';
import { env } from '$env/dynamic/private';
import { detectConflict, type ExistingSessionDigest } from './sessionConflict';
import {
	signPendingLoginToken,
	type PendingLoginRole,
	type PendingLoginCollection
} from './pendingLoginToken';

/**
 * Read at runtime via `$env/dynamic/private` (NOT `$env/static/private`)
 * because the env var is optional — unset = soak mode by default, so
 * developers + CI don't need to provision anything. Production flip
 * happens at Commit C by setting `SESSION_ENFORCEMENT_KICK_ENABLED='true'`
 * on the Vercel `rinn` project (Production + Preview + Development).
 *
 * Resolved lazily on every call rather than cached at module load —
 * keeps the soak→enforce transition immediate without requiring a
 * function redeploy after the env var flip.
 */
function isKickEnabled(): boolean {
	return env.SESSION_ENFORCEMENT_KICK_ENABLED === 'true';
}

export interface GateInput {
	/** The resolved user's ObjectId (DSA/RM/Admin/Applicant collection). */
	userId: ObjectId;
	/** Sessions.user_role flavour ('admin' | 'dsa' | 'rm' | 'applicant'). */
	userRole: PendingLoginRole;
	/**
	 * Which collection the user was resolved from. Stored in the
	 * pending-login-token so login-confirm can `_id`-lookup the right
	 * collection — userRole alone isn't sufficient since 'admin' can come
	 * from either AdminUsers or Applicant.
	 */
	userCollection: PendingLoginCollection;
	/**
	 * Pre-generated tokenId. The caller hoists generateTokenId() to the
	 * top of the handler; the same value is used here (signed into the
	 * pending-login-token on conflict) or downstream (minted as the
	 * refresh JWT tokenId on no-conflict).
	 */
	tokenId: string;
	/**
	 * The sanitized fingerprint inputs already computed in check-dsa
	 * from the request body (sanitizeFingerprint + sanitizeClientClass
	 * outputs spread into sessionExtras).
	 */
	sanitizedFingerprints: {
		device_fingerprint?: string;
		browser_fingerprint?: string;
		client_class?: 'web' | 'android';
	};
}

/**
 * The response body returned to the client when a conflict is detected
 * AND the kick env flag is enabled. Matches the spec §5 Step 1 contract.
 */
export interface SessionConflictResponseBody {
	status: 'session_conflict';
	existing_sessions: ExistingSessionDigest[];
	pending_login_token: string;
}

export type GateResult =
	| { kind: 'conflict'; body: SessionConflictResponseBody }
	| { kind: 'proceed' };

/**
 * Run the conflict gate. NEVER throws — a DB failure or telemetry failure
 * resolves to 'proceed' so a transient Sessions-collection problem can't
 * lock the whole login endpoint out. Security posture: the device-switch
 * nuke via activeTokenIds[] in hooks.server.ts:122 is still in place
 * during the dual-write window; SEC-10 is additive enforcement, not the
 * sole gate.
 */
export async function evaluateLoginConflict(input: GateInput): Promise<GateResult> {
	const { userId, userRole, userCollection, tokenId, sanitizedFingerprints } = input;

	let existingRows;
	try {
		// Bounded read — a single user holds at most ~10 active sessions
		// (activeTokenIds cap), so the result set is small. Partial index
		// {user_id:1, revoked_at:1} from mongo.ts:1182 makes this cheap.
		existingRows = await Sessions.find(
			{ user_id: userId, revoked_at: null },
			{
				projection: {
					session_id: 1,
					device_label: 1,
					device_fingerprint: 1,
					browser_fingerprint: 1,
					client_class: 1,
					last_seen_at: 1
				}
			}
		).toArray();
	} catch (err) {
		// Fail-open: a Sessions-query blip should not block legitimate
		// logins. Log at warn so ops can investigate if persistent.
		logger.warn(
			{ err, userId: String(userId), userRole },
			'[sec-10] conflict-gate Sessions query failed — proceeding without enforcement'
		);
		return { kind: 'proceed' };
	}

	const report = detectConflict(existingRows as never, {
		device_fingerprint: sanitizedFingerprints.device_fingerprint,
		browser_fingerprint: sanitizedFingerprints.browser_fingerprint,
		client_class: sanitizedFingerprints.client_class,
		incoming_token_id: tokenId
	});

	// Silent rotation — same-browser re-login predecessors are revoked
	// server-side BEFORE the modal-vs-proceed branch below, because both
	// branches need this cleanup. Without this, the prior Sessions row
	// sits in Atlas with `revoked_at == null` forever (the user's cookie
	// has already been rotated by the new login, so the old session_id
	// is unreachable, but the row still inflates active-session counts
	// and pollutes future conflict-detection runs). See ConflictReport
	// JSDoc + Pitfall #77 for the regression history.
	//
	// Hygiene-only failure mode: if updateMany throws (transient Atlas
	// hiccup, network partition), the new login still succeeds — we log
	// a warn and move on. The ghost row will be cleaned up by either the
	// next same-browser re-login (same silent_session_ids set) or by the
	// eventual TTL-on-revoked-rows policy (separate PR).
	if (report.silent_session_ids.length > 0) {
		try {
			const result = await Sessions.updateMany(
				{
					user_id: userId,
					session_id: { $in: report.silent_session_ids },
					revoked_at: null
				},
				{
					$set: {
						revoked_at: new Date(),
						revoke_reason: 'rotated_same_browser'
					}
				}
			);
			logger.info(
				{
					event: 'session.silent_rotated',
					userId: String(userId),
					userRole,
					silent_count: report.silent_session_ids.length,
					modified: result.modifiedCount
				},
				'[sec-10] silent rotation — same-browser predecessors revoked'
			);
		} catch (err) {
			logger.warn(
				{
					err,
					userId: String(userId),
					userRole,
					silent_session_ids: report.silent_session_ids
				},
				'[sec-10] silent rotation revoke failed — proceeding (hygiene-only failure)'
			);
		}
	}

	// Only modal-producing rows are worth surfacing in telemetry +
	// blocking-modal flow. Silent rows were handled above.
	const hasModal = report.modal_sessions.length > 0;
	if (!hasModal) {
		return { kind: 'proceed' };
	}

	// Telemetry — emitted whether we kick or just observe. The admin
	// dashboard counts these to drive the kick-rate widget + tune the
	// fingerprint heuristics during soak.
	const kickEnabled = isKickEnabled();
	const conflictTypes = Array.from(
		new Set(report.modal_sessions.map((s) => s.conflict_type))
	);
	logger.info(
		{
			event: 'session.conflict_detected',
			userId: String(userId),
			userRole,
			conflict_types: conflictTypes,
			existing_session_count: report.modal_sessions.length,
			kick_enabled: kickEnabled
		},
		'[sec-10] session conflict detected'
	);

	// Soak mode (default): observe only. Login proceeds normally; the
	// new Sessions row will be inserted alongside the existing ones,
	// activeTokenIds[] retains the device-switch-nuke semantics.
	if (!kickEnabled) {
		return { kind: 'proceed' };
	}

	// Enforcement mode: build the pending-login-token + return the
	// session_conflict response. Caller skips token issuance entirely.
	let pendingToken: string;
	try {
		pendingToken = signPendingLoginToken({
			userId: String(userId),
			userRole,
			userCollection,
			tokenId,
			kickEligibleSessionIds: report.modal_sessions.map((s) => s.id),
			incomingFingerprints: {
				device_fingerprint: sanitizedFingerprints.device_fingerprint,
				browser_fingerprint: sanitizedFingerprints.browser_fingerprint,
				client_class: sanitizedFingerprints.client_class
			}
		});
	} catch (err) {
		// Signing failure (e.g. JWT_SECRET unset) — fail-open to a normal
		// login. The alternative (block login entirely) trades a real
		// security boundary for a feature that's only days old in prod.
		logger.error(
			{ err, userId: String(userId), userRole },
			'[sec-10] pending-login-token sign failed — proceeding without enforcement'
		);
		return { kind: 'proceed' };
	}

	return {
		kind: 'conflict',
		body: {
			status: 'session_conflict',
			existing_sessions: report.modal_sessions,
			pending_login_token: pendingToken
		}
	};
}
