/**
 * Synthetic Profile Definitions -- 500 deterministic profiles
 * Generated by syntheticGenerator.ts from demographic archetypes.
 *
 * Replaces the previous 23 hand-crafted profiles with a generator that
 * covers all 6 loan types, employment types, city tiers, and edge cases.
 * Same seed -> same 500 profiles every time.
 */

import { generateAllProfiles } from '$lib/testing/generators/syntheticGenerator.js';

const generated = generateAllProfiles();

export const syntheticProfiles = generated;
