/**
 * Plot Character & Ownership Questions
 * Page: propertyCharacter_Plot
 */

import type { RawSchemaQuestion } from '../../schema/schemaTypes.js';

export const q1_purchaseType: RawSchemaQuestion = {
	id: 'q1_purchaseType',
	bindsTo_template: 'purchaseType',
	contextKey: 'purchaseType',
	type: 'radio',
	radioClass: 'mt-[2rem] md:mt-[3rem]',
	optionContainerClass: 'grid gap-3',
	uiGroup: 'radio_fields',
	uiMeta: {
		icon: 'map-pinned'
	},
	required: true,
	question: 'What is the nature of plot purchase?',
	description:
		"<div class='info-title'><span class='info-icon gold'>🤝</span> Nature of Plot Purchase</div><div class='info-box highlight'>The loan process varies based on who you are purchasing the plot from. Authority allotments and developer projects get the best lender acceptance.</div>",
	options: [
		{
			label: 'Direct from Development Authority (DDA, HUDA, BDA, etc.)',
			value: 'direct_from_authority',
			icon: 'Landmark',
			helperText: 'Allotment from DDA, HUDA, BDA, PCMC, or similar development authority',
			showWhen: {
				in: [{ var: 'propertyAreaType' }, ['PLANNED_AUTHORITY', 'UNKNOWN', '']]
			}
		},
		{
			label: 'Direct from Developer / Township',
			value: 'direct_from_developer',
			icon: 'Building2',
			helperText: 'RERA-registered developer project or plotted township',
			showWhen: {
				in: [
					{ var: 'propertyAreaType' },
					['PLANNED_AUTHORITY', 'CONVERTED_RESIDENTIAL', 'UNKNOWN', '']
				]
			}
		},
		{
			label: 'Resale / Individual purchase',
			value: 'resale',
			icon: 'ArrowLeftRight',
			helperText: 'Buying from an individual or entity who currently owns the plot'
		}
	],
	showWhen: {
		'!=': [
			{
				var: 'landUseClassification'
			},
			''
		]
	}
};

export const q2_developmentAuthority: RawSchemaQuestion = {
	id: 'q2_developmentAuthority',
	bindsTo_template: 'developmentAuthority',
	contextKey: 'developmentAuthority',
	type: 'select',
	selectClass: 'mt-8 md:mt-12',
	uiGroup: 'select_fields',
	searchBarNeeded: true,
	uiMeta: {
		placeholder: 'Select development authority',
		icon: 'landmark'
	},
	required: true,
	question: 'Which development authority allotted this plot?',
	description: 'Select the government development authority that originally allotted this plot.',
	// Options are dynamically generated by optionResolver based on the selected
	// property city/state from developmentAuthorities.json — same resolver as
	// Home Loan's q1_authorityName. Static options below are fallbacks only,
	// used if city is not yet set.
	options: [
		{ label: 'Military / Defence authority (e.g., Army Welfare Housing)', value: 'DEFENCE' },
		{ label: 'Other authority', value: 'OTHER' }
	],
	showWhen: {
		'==': [
			{
				var: 'purchaseType'
			},
			'direct_from_authority'
		]
	}
};

export const q1_propertyType: RawSchemaQuestion = {
	id: 'q1_propertyType',
	bindsTo_template: 'propertyType',
	contextKey: 'propertyType',
	type: 'radio',
	radioClass: 'mt-[1rem] md:mt-[2rem]',
	labelClass: 'text-black',
	optionContainerClass: 'grid md:grid-cols-2 gap-3',
	uiGroup: 'radio_fields',
	description:
		"<div class='info-title'><span class='info-icon gold'>🏠</span> Property Ownership Type</div><div class='info-box highlight'>The type of ownership determines your rights over the property and affects loan eligibility.</div><div class='info-divider'></div><div class='visual-diagram'><div class='diagram-row'><span class='diagram-label'><span class='tag green'>Freehold</span></span><span class='diagram-value'>Full ownership rights forever</span></div><div class='diagram-row'><span class='diagram-label'><span class='tag blue'>Leasehold</span></span><span class='diagram-value'>Rights for a specific period</span></div></div><div class='info-box note'><span class='bold'>📌 Key Points:</span><ul class='info-list'><li>Freehold properties are preferred by most lenders</li><li>Leasehold requires checking remaining lease period</li><li>Some lenders may need lease extension proof</li></ul></div>",
	question: 'Please indicate the type of ownership for the property?',
	required: true,
	options: [
		{
			label: 'Lease Hold',
			value: 'Lease Hold',
			uiMeta: {
				icon: 'Circle'
			},
			icon: 'FileKey'
		},
		{
			label: 'Free Hold',
			value: 'Free Hold',
			uiMeta: {
				icon: 'Circle'
			},
			icon: 'FileText'
		}
	],
	showWhen: {
		'!=': [
			{
				var: 'purchaseType'
			},
			''
		]
	}
};

export const q4_leaseRemainingPeriod: RawSchemaQuestion = {
	id: 'q4_leaseRemainingPeriod',
	bindsTo_template: 'leaseRemainingPeriod',
	contextKey: 'leaseRemainingPeriod',
	type: 'select',
	selectClass: 'mt-8 md:mt-12',
	uiGroup: 'select_fields',
	uiMeta: {
		placeholder: 'Select remaining lease period',
		icon: 'calendar'
	},
	required: true,
	question: 'How many years are remaining on the lease?',
	options: [
		{
			label: 'More than 30 years',
			value: 'MORE_THAN_30'
		},
		{
			label: '20 to 30 years',
			value: '20_TO_30'
		},
		{
			label: '10 to 20 years',
			value: '10_TO_20'
		},
		{
			label: 'Less than 10 years',
			value: 'LESS_THAN_10'
		}
	],
	showWhen: {
		'==': [
			{
				var: 'propertyType'
			},
			'Lease Hold'
		]
	},
	warning: {
		condition: [
			{
				case: {
					in: [
						{
							var: 'leaseRemainingPeriod'
						},
						['10_TO_20', 'LESS_THAN_10']
					]
				},
				then: 'Leasehold properties with less than 20 years remaining are extremely difficult to finance. Most banks will reject.'
			}
		]
	}
};

export const q5_plotAge: RawSchemaQuestion = {
	id: 'q5_plotAge',
	bindsTo_template: 'plotAge',
	contextKey: 'plotAge',
	type: 'select',
	selectClass: 'mt-8 md:mt-12',
	uiGroup: 'select_fields',
	uiMeta: {
		placeholder: 'Select plot age',
		icon: 'calendar'
	},
	required: true,
	question: 'When was this plot first allotted or sold?',
	description:
		'Select the approximate age since the plot was first allotted by authority or first sold. This helps determine title chain requirements.',
	options: [
		{
			label: 'Less than 5 years',
			value: '0-5'
		},
		{
			label: '5–10 years',
			value: '5-10'
		},
		{
			label: '10–20 years',
			value: '10-20'
		},
		{
			label: '20–30 years',
			value: '20-30'
		},
		{
			label: 'More than 30 years',
			value: '30+'
		}
	],
	showWhen: {
		'!=': [
			{
				var: 'propertyType'
			},
			''
		]
	}
};

export const q6_PlotArea: RawSchemaQuestion = {
	id: 'q6_PlotArea',
	bindsTo_template: 'PlotArea',
	contextKey: 'PlotArea',
	type: 'text',
	uiType: 'number',
	textClass: 'mt-8 md:mt-12',
	uiGroup: 'number_fields',
	uiMeta: {
		placeholder: 'Enter total area of plot',
		showAreaUnitDropdown: true,
		showNumberInWords: true,
		maxLength: 6
	},
	required: true,
	minLimit: 100,
	maxLimit: 1000000,
	question: 'What is the total area of Plot?',
	validation: {
		condition: [
			{
				case: {
					'>': [
						{
							var: 'PlotArea'
						},
						1000000
					]
				},
				then: 'Area should not be greater than 10,00,000'
			}
		]
	},
	showWhen: {
		'!=': [
			{
				var: 'plotAge'
			},
			''
		]
	}
};

export const q7_plotBoundaryStatus: RawSchemaQuestion = {
	id: 'q7_plotBoundaryStatus',
	bindsTo_template: 'plotBoundaryStatus',
	contextKey: 'plotBoundaryStatus',
	type: 'radio',
	radioClass: 'mt-8 md:mt-12',
	optionContainerClass: 'grid md:grid-cols-2 gap-3',
	uiGroup: 'radio_fields',
	uiMeta: {
		icon: 'square-dashed-bottom'
	},
	required: true,
	question: 'What is the boundary demarcation status of this plot?',
	description:
		"<div class='info-box highlight'>Banks require clear boundary demarcation for physical verification and valuation. Unclear boundaries can delay or prevent loan approval.</div>",
	options: [
		{
			label: 'Clear demarcation with boundary stones',
			value: 'clear_demarcation',
			icon: 'CheckCircle'
		},
		{
			label: 'Partially demarcated',
			value: 'partially_demarcated',
			icon: 'AlertTriangle'
		},
		{
			label: 'No clear boundaries',
			value: 'no_boundaries',
			icon: 'XCircle'
		},
		{
			label: 'Compound wall / fencing exists',
			value: 'compound_wall',
			icon: 'Fence'
		}
	],
	showWhen: {
		and: [
			{
				'!=': [
					{
						var: 'plotArea'
					},
					''
				]
			},
			{
				'!=': [
					{
						var: 'plotArea'
					},
					null
				]
			}
		]
	},
	warning: {
		condition: [
			{
				case: {
					'==': [
						{
							var: 'plotBoundaryStatus'
						},
						'no_boundaries'
					]
				},
				then: 'Banks require clear boundary demarcation for physical verification. This may delay or prevent loan approval. Consider getting a boundary survey done before applying.'
			}
		]
	}
};

/** Returns all questions for the Plot Character & Ownership page */
export function getPropertyCharacterPlotQuestions(): RawSchemaQuestion[] {
	return [
		q1_purchaseType,
		q2_developmentAuthority,
		q1_propertyType,
		q4_leaseRemainingPeriod,
		q5_plotAge,
		q6_PlotArea,
		q7_plotBoundaryStatus
	];
}
